"""Reserved PTX token vocabulary from the pinned ptxas lexer automaton, plus its opcode registry.

Only reserved actions 60..526 are vocabulary: generic identifiers (528/529) accept almost anything.
Usage: python3 lexer_vocab.py /path/to/ptxas lexer_vocab.json dict/ptx-lexer.dict
"""
import json, re, struct, sys
from collections import defaultdict
from pathlib import Path
from pinned import loader, PINNED

HERE=Path(__file__).resolve().parent
START_STATES,ACTIONS,ACTION_RETURN=0x203c020,0x203a5a8,0x7211d6
RESERVED=range(60,527)
KNOWN={'.rn':160,'.u32':258,'.f32':279,'.eq':74,'.cc':112,'.global':66,'.ca':148,'.wb':153,'.uni':193,'mad.wide':528}
# Comment actions read the rest of the comment themselves, through this terminator.
COMMENTS={545:b'\n',544:b'*/'}
ABSENT=['.rq','.rx','.blorp','.r','banana','papaya','%r1']

def automaton(read):
    """flex -F table: entry {u32 check, i32 next} at state+8*c; accept action u32 at state-4."""
    u32=lambda a: struct.unpack('<I',read(a,4))[0]
    def step(state,c):
        try: check,offset=struct.unpack('<Ii',read(state+8*c,8))
        except ValueError: return None
        return state+8*offset if check==c else None
    start=struct.unpack('<Q',read(START_STATES+8,8))[0]
    index={start:0}; order=[start]; edges=[]
    for state in order:
        out={}
        for c in range(1,128):
            n=step(state,c)
            if n is not None:
                out[c]=index.setdefault(n,len(order))
                if out[c]==len(order): order.append(n)
        edges.append(out)
    return [[u32(s-4),out] for s,out in zip(order,edges)]

def vocabulary(dfa):
    """Strings whose final state accepts a reserved action, walking only states that can reach one."""
    useful={i for i,(a,_) in enumerate(dfa) if a in RESERVED}
    changed=True
    while changed:
        changed=False
        for i,(_,out) in enumerate(dfa):
            if i not in useful and useful.intersection(out.values()): useful.add(i); changed=True
    found=defaultdict(list); path=set()
    def walk(i,text):
        if i in path: raise AssertionError(f'Reserved rule with an infinite language near {text!r}')
        path.add(i)
        if dfa[i][0] in RESERVED: found[dfa[i][0]].append(text)
        for c,n in dfa[i][1].items():
            if n in useful: walk(n,text+chr(c))
        path.discard(i)
    walk(0,'')
    return found

def returned_token(read,action):
    """Handlers set yylval, then `mov $token,%eax; jmp ACTION_RETURN`."""
    address=struct.unpack('<Q',read(ACTIONS+8*action,8))[0]
    code=read(address,200)
    for m in re.finditer(rb'\xb8(....)\xe9(....)',code,re.S):
        if address+m.end()+struct.unpack('<i',m.group(2))[0]==ACTION_RETURN: return struct.unpack('<I',m.group(1))[0]
    raise AssertionError(f'Unrecognized handler for action {action} at {address:#x}')

def lex(dfa,data):
    """Longest match with backup from the normal start condition: [(start, end, action)]."""
    tokens=[]; at=0
    while at<len(data):
        state,i,last=0,at,None
        while i<len(data) and (n:=dfa[state][1].get(data[i])) is not None:
            state=n; i+=1
            if dfa[state][0]: last=(i,dfa[state][0])
        if last is None: tokens.append((at,at+1,None)); at+=1
        else:
            tokens.append((at,*last)); at=last[0]
            if last[1] in COMMENTS:
                end=data.find(COMMENTS[last[1]],at)
                at=len(data) if end<0 else end+len(COMMENTS[last[1]])
    return tokens

def action_of(dfa,text):
    matched=lex(dfa,text.encode())
    return matched[0][2] if len(matched)==1 else None

def extract(binary):
    read=loader(binary)
    dfa=automaton(read)
    found=vocabulary(dfa)
    for text,action in KNOWN.items(): assert action_of(dfa,text)==action,(text,action_of(dfa,text))
    strings={s for ss in found.values() for s in ss}
    assert not strings.intersection(ABSENT),strings.intersection(ABSENT)
    assert 400<=len(strings)<=600,len(strings)
    classes=defaultdict(list)
    for action,ss in sorted(found.items()): classes[returned_token(read,action)].append(dict(action=action,strings=sorted(ss)))
    return dict(compiler_sha256=PINNED,dfa=dfa,classes=dict(sorted(classes.items())))

def quote(text): return '"'+''.join(c if c.isprintable() and c not in '"\\' else f'\\x{ord(c):02x}' for c in text)+'"'

def dictionary(vocab,registry):
    lines=['# Generated by lexer_vocab.py from the pinned CUDA 13.0.88 ptxas; do not edit.',
           '# Reserved lexer tokens grouped by returned parser token, then registered opcode names.']
    for token,actions in vocab['classes'].items():
        lines.append(f'# token {token}')
        lines.extend(quote(s) for a in actions for s in a['strings'])
    names=sorted(set(registry['names'])|set(registry['roots']))
    lines.append(f'# registered opcodes ({len(names)})')
    lines.extend(quote(s) for s in names)
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    vocab=extract(sys.argv[1])
    registry=json.loads((HERE/'opcode_registry.json').read_text())
    assert registry['compiler_sha256']==PINNED
    Path(sys.argv[2]).write_text(json.dumps({k:v for k,v in vocab.items() if k!='dfa'},indent=1)+'\n')
    Path(sys.argv[3]).write_text(dictionary(vocab,registry))
    print(f"{len(vocab['dfa'])} states, {sum(len(a['strings']) for c in vocab['classes'].values() for a in c)} reserved strings, "
          f"{len(vocab['classes'])} classes")
