[package]
name = "ptx-sass-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
libafl = { git = "https://github.com/AFLplusplus/LibAFL", rev = "70259b66bcbdc322b81ee59e71d83f27e0187c35" }
libafl_targets = { git = "https://github.com/AFLplusplus/LibAFL", rev = "70259b66bcbdc322b81ee59e71d83f27e0187c35" }
libafl_bolts = { git = "https://github.com/AFLplusplus/LibAFL", rev = "70259b66bcbdc322b81ee59e71d83f27e0187c35" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard = { version = "1", features = ["alloc"] }
libc = "0.2"

[profile.release]
opt-level = 3
